### ISSUE TITLE
隔壁那个网站不能访问啊

### ISSUE THREAD

**Issue by srayuws** [xindejiayuan/xindejiayuan.github.io#4]
A GNU Social-compatible microblogging server https://xindejiayuan.com.org
就这个

**Comment by aisk** [comment]
贵高大上的家园怎么会用 .org 域名，实际域名是 https://xindejiayuan.com 。

**Comment by srayuws** [comment]
所以那个描述要不要改一下

**Comment by aisk** [comment]
改了。
